# Generated by Django 2.1 on 2018-11-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20181107_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, max_length=100)),
                ('semestru', models.IntegerField(blank=True, null=True)),
                ('puncte_credit', models.IntegerField(blank=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='SituatieScolara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('admis', models.BooleanField(default=False)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='situatie_scolara.Materii')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cel_notat', to='accounts.Student')),
            ],
        ),
    ]
