# Generated by Django 2.1 on 2018-12-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('situatie_scolara', '0006_auto_20181205_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locatii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpul', models.CharField(blank=True, max_length=100)),
                ('sala', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziua_saptamanala', models.CharField(blank=True, max_length=100)),
                ('anul', models.CharField(blank=True, max_length=100)),
                ('tip', models.CharField(blank=True, max_length=100)),
                ('locatia', models.ForeignKey(on_delete='cascade', to='orar.Locatii')),
                ('materia', models.ForeignKey(on_delete='cascade', to='situatie_scolara.Materii')),
            ],
        ),
    ]
