# Generated by Django 2.1 on 2018-12-06 17:40

from django.db import migrations
import orar.models


class Migration(migrations.Migration):

    dependencies = [
        ('orar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orar',
            name='intervalul_orar',
            field=orar.models.IntervalOrarField(blank=True, choices=[('1', '8-10'), ('2', '10-12'), ('3', '12-14'), ('4', '14-16'), ('5', '16-18'), ('6', '18-20'), ('7', '20-22')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orar',
            name='ziua_saptamanala',
            field=orar.models.DayOfTheWeekField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1),
        ),
    ]
